
#line 2 "lex.yy.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

    /* The c++ scanner is a mess. The FlexLexer.h header file relies on the
     * following macro. This is required in order to pass the c++-multiple-scanners
     * test in the regression suite. We get reports that it breaks inheritance.
     * We will address this in a future release of flex, or omit the C++ scanner
     * altogether.
     */
    #define yyFlexLexer yyFlexLexer

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */
#include <iostream>
#include <errno.h>
#include <cstdlib>
#include <cstdio>
#include <cstring>
/* end standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{

	std::streambuf* yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

#define yytext_ptr yytext
#define YY_INTERACTIVE

#include <FlexLexer.h>

int yyFlexLexer::yywrap() { return 1; }

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 9
#define YY_END_OF_BUFFER 10
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[365] =
    {   0,
        0,    0,   10,    8,    7,    7,    2,    8,    4,    2,
        2,    8,    3,    2,    2,    2,    3,    2,    5,    5,
        2,    2,    2,    2,    2,    2,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    2,    2,    0,    5,    4,    0,    0,    5,
        0,    6,    5,    5,    0,    0,    5,    0,    5,    0,
        0,    0,    0,    5,    0,    3,    2,    2,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    1,    4,
        4,    4,    4,    4,    4,    4,    4,    1,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,

        4,    4,    4,    4,    4,    4,    4,    0,    5,    5,
        0,    0,    0,    0,    6,    5,    5,    0,    5,    0,
        5,    0,    0,    5,    0,    5,    0,    5,    5,    0,
        5,    0,    5,    5,    0,    5,    0,    2,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    1,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    0,    0,    0,    5,    0,    0,    5,    0,    6,
        5,    0,    0,    5,    5,    0,    5,    5,    0,    5,

        5,    0,    0,    0,    5,    5,    0,    0,    5,    0,
        5,    0,    0,    0,    5,    0,    5,    0,    5,    0,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    0,    0,    0,    5,
        0,    0,    0,    5,    0,    5,    0,    5,    0,    5,
        0,    0,    0,    5,    0,    0,    5,    5,    0,    5,
        0,    0,    0,    5,    0,    5,    0,    4,    4,    4,
        4,    4,    4,    4,    1,    4,    4,    4,    4,    4,

        4,    4,    4,    4,    4,    4,    4,    4,    4,    1,
        4,    4,    0,    5,    0,    5,    0,    0,    0,    5,
        5,    0,    0,    0,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        5,    0,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    1,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       23,   23,   23,   23,   23,   24,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   32,   34,   35,   36,
       37,   37,   37,   37,   37,   38,   37,   37,   37,   39,
       37,   37,   37,   37,   37,   37,   37,   40,   37,   37,
       41,    1,   42,   43,   44,    1,   45,   46,   47,   48,

       49,   50,   51,   52,   53,   54,   55,   56,   57,   58,
       59,   60,   54,   61,   62,   63,   64,   65,   66,   67,
       68,   69,   70,   71,   72,   73,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[74] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    1,    4,    1,
        1,    5,    1,    1,    1,    1,    1,    1,    6,    1,
        7,    7,    7,    7,    1,    1,    1,    1,    1,    1,
        1,    7,    7,    7,    7,    7,    4,    8,    9,    4,
        1,    1,    1,    9,    7,    7,    7,    7,    7,    7,
        4,    4,    4,    4,    4,    8,    4,    4,    4,    9,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    1,
        1,    1,    1
    } ;

static const flex_int16_t yy_base[385] =
    {   0,
        0,    0,  972,  973,  973,  973,  943,  962,    0,  941,
       63,    0,  973,  940,   59,   60,   58,   70,   80,  129,
      942,   56,  938,   64,  973,  937,   48,   64,   82,   27,
       39,   86,  905,   50,  904,   95,  110,  913,   94,   44,
      902,  908,   83,  973,  951,  950,    0,  945,  937,  165,
      940,    0,  169,  199,  189,  100,  973,  208,  973,  935,
      217,  147,  934,  225,  229,  973,  924,  147,  889,  888,
      890,  899,  884,  118,  901,  900,  886,  893,  878,  879,
      876,  876,  882,  879,  877,  874,  871,    0,  873,  120,
      874,  868,  864,  873,  881,   84,  880,  860,  857,   72,

      849,  808,  788,  141,  190,   56,  791,  260,  253,  973,
      262,  266,  828,  141,    0,  290,  973,  277,  283,    0,
      973,  297,  307,  311,  174,  322,    0,  335,  338,  341,
      331,    0,  358,  377,  382,  386,  401,  810,  774,  780,
      772,  778,  773,  772,  772,  757,  755,  144,  771,  769,
      765,  756,  760,  746,  762,  761,  742,  169,  733,  745,
      742,  739,  728,  728,  717,  717,  719,  705,  706,  703,
      710,  694,  677,  692,  674,  676,  675,  682,  681,  681,
      668,  429,  714,  264,    0,  415,  419,  426,  706,  973,
      431,  442,  456,  460,    0,  467,  471,  973,  235,  478,

      973,  495,  263,  110,  486,  973,  513,  494,  367,  534,
      523,  238,  332,  231,  521,  524,    0,  548,  552,  564,
      647,  643,  652,  645,  639,  625,  609,  613,  596,  596,
      586,  594,  585,  575,  588,  570,  576,  558,  553,    0,
      572,  564,  558,  553,  540,  531,  540,  544,  528,  536,
      530,  500,  502,    0,  490,  503,  543,  541,  540,  576,
      581,  532,  288,    0,  592,  606,  611,  601,  372,  625,
      641,  407,  551,  632,    0,  655,  659,    0,  675,  646,
      451,  614,  650,  667,    0,    0,  690,  496,  460,  476,
      462,  451,  457,  455,  442,  440,  424,  427,  421,  420,

      417,  398,  411,  410,  398,  397,  366,  376,  366,  358,
      366,  364,  407,  694,  724,  728,  733,  681,  693,  737,
      973,  767,  726,  735,  366,  354,  322,  321,  321,  313,
      331,  331,  323,  308,  301,  285,  297,  283,  288,  280,
      776,  781,  272,  273,  259,  267,  268,  260,  236,  236,
      234,  232,  208,  209,  195,  194,  183,  171,  154,  158,
      115,  123,  118,  973,  826,  832,  841,  850,  859,  863,
      865,  872,  128,  876,  112,  880,  889,  898,  901,  905,
      908,  912,  915,  918
    } ;

static const flex_int16_t yy_def[385] =
    {   0,
      364,    1,  364,  364,  364,  364,  364,  365,  366,  364,
      364,  367,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  364,  364,  365,  364,  366,  364,  364,  364,
      368,  369,  364,   20,   54,  364,  364,  364,  364,  370,
      364,  364,  371,   20,  364,  364,  364,  364,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,

      366,  366,  366,  366,  366,  366,  366,  364,   50,  364,
      364,  364,  368,  372,  369,  364,  364,  364,   54,   55,
      364,  364,  364,  364,  364,  364,  373,  374,   54,  364,
      364,  375,  376,   20,  364,   20,  364,  364,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  364,  377,  377,  109,  364,  364,  364,  378,  364,
      116,  364,  364,  364,  119,  364,  364,  364,  364,  364,

      364,  364,  379,  373,  380,  364,  364,  380,  119,  364,
      364,  364,  381,  375,  382,  382,  134,  364,  134,  364,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  377,  377,  377,  364,
      364,  378,  372,  191,  364,  364,  364,  364,  364,  364,
      364,  383,  383,  208,  208,  364,  364,  209,  364,  364,
      364,  384,  384,  216,  216,  219,  364,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,

      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  377,  364,  364,  364,  364,  383,  383,  364,
      364,  364,  384,  384,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      364,  364,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,    0,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364
    } ;

static const flex_int16_t yy_nxt[1047] =
    {   0,
        4,    5,    6,    5,    5,    5,    7,    8,    9,   10,
       11,   12,   13,   13,   14,   15,   13,   16,   17,   18,
       19,   20,   20,   20,   21,   13,   22,   23,   24,   25,
       13,    9,    9,    9,    9,    9,    9,    9,    9,    9,
       13,   13,   26,    9,   27,   28,   29,   30,   31,   32,
       33,    9,   34,    9,    9,   35,    9,   36,    9,   37,
       38,   39,   40,    9,   41,   42,    9,    9,    9,   13,
       43,   13,   25,   44,   44,   78,   49,   44,   50,   50,
       50,   50,   67,   44,   51,   79,   44,   44,   44,   52,
       44,   44,   68,   69,   80,  104,   81,   44,   53,   88,

       54,   54,   54,   55,  105,   82,   89,   90,  179,   70,
       44,  180,   56,   57,   58,   57,  170,   59,  213,   60,
      124,  124,   71,   61,   72,   62,   74,   57,   58,   57,
       83,   73,  171,   75,  203,   59,  165,   76,   84,   92,
       77,   85,  166,   93,   86,   99,   63,   53,  207,   64,
       64,   64,   64,   44,   95,  114,  100,  101,   94,  102,
      190,  103,   57,   58,   57,   88,   59,  131,  131,  207,
       96,  363,   65,   97,   44,  138,   57,   58,   57,  144,
      145,  159,  160,  362,   59,  109,  109,  109,  109,  116,
      116,  116,  116,  175,  126,  126,  126,  126,  110,  111,

      110,  176,  117,  118,  117,  227,  228,   88,  112,  120,
      120,  120,  110,  111,  110,   88,  117,  118,  117,  119,
      119,  119,  120,  125,  235,  125,  364,  236,  126,  126,
      126,  126,  123,   88,  177,  361,  121,  129,  129,  129,
      120,   88,  122,   88,  364,  134,  134,  134,  134,  136,
      136,  136,  136,  178,  121,  268,  268,   88,  280,  280,
      130,  182,  183,  182,  184,  182,  259,  360,  135,  207,
      359,  258,  137,  185,  185,  185,  185,  187,  269,  187,
       88,  281,  188,  188,  188,  188,  185,  185,  185,  185,
      207,  358,  193,  357,  193,   88,  186,  194,  194,  194,

      194,  207,  263,  195,  195,  195,  273,  190,  356,  186,
      191,  191,  191,  191,  355,  354,  353,  195,  195,  195,
      120,   88,  207,  117,  118,  117,  196,  120,  120,  120,
      120,  197,  197,  192,   88,  352,  351,  117,  118,  117,
      196,  350,  200,  200,  200,  200,  349,  348,  198,   88,
      123,  211,  211,  204,  199,  201,   88,  201,  209,  209,
      209,  129,  129,  129,  120,  202,  198,  347,  198,  201,
      207,  201,  206,  207,  212,  283,  214,  346,  208,  345,
       88,  210,   88,   88,  130,  344,  198,  278,  278,  278,
      206,  207,  268,  268,  207,  206,  207,  217,  217,  217,

      217,  216,  217,  217,  217,  217,  219,  219,  219,  219,
      279,   88,  343,  206,   59,  269,  340,  207,  339,   88,
      218,  136,  136,  136,  136,  218,  338,   88,  337,  220,
      182,  183,  182,  184,  182,  185,  185,  185,  185,  188,
      188,  188,  188,   88,  137,  207,  260,  260,  260,  260,
      319,  264,  264,  264,  264,   88,   88,  336,  186,  110,
      335,  110,  264,  264,  264,  264,  207,  334,   88,  261,
      333,  280,  280,  110,  265,  110,  194,  194,  194,  194,
      266,  266,  266,  266,  332,  265,   88,  195,  195,  195,
      120,  268,  268,  117,  281,  117,  331,  330,  270,  270,

      270,  270,  329,  267,  204,   88,  328,  117,  198,  117,
      196,  201,  364,  201,  269,  270,  270,  270,  270,  327,
      326,  271,   88,  206,  207,  201,  198,  201,  276,  275,
      276,  364,  364,  277,  277,  277,  277,  275,  271,  214,
      325,  206,  364,  280,  280,  207,  263,  258,  313,  364,
      258,   88,  312,  364,  278,  278,  278,  120,  206,  207,
      198,  364,  364,  311,  285,  310,  281,  285,  217,  217,
      217,  217,  286,  286,  286,  286,  206,  279,  198,  364,
      207,  309,  308,  364,  286,  286,  286,  286,   88,  364,
      307,  218,  306,   88,  319,  287,  314,  314,  314,  314,

      305,  314,  314,  314,  314,  304,  303,  287,  302,  110,
      364,  110,  264,  264,  264,  264,  301,  300,  299,  315,
      298,  268,  268,  110,  315,  110,  316,  316,  316,  316,
      297,  316,  316,  316,  316,  265,  296,   88,  198,  117,
      295,  117,  254,  294,  269,  270,  270,  270,  270,  317,
      204,  293,  207,  117,  317,  117,  198,  324,  201,  292,
      201,  270,  270,  270,  270,  291,  280,  280,  271,  206,
      207,   88,  201,  207,  201,  277,  277,  277,  277,  320,
      320,  320,  320,  198,  271,  214,   88,  206,  364,  281,
       88,  207,  321,  324,  321,  278,  278,  278,  120,   88,

      290,  198,  322,  289,  206,  207,  321,  288,  321,  364,
      286,  286,  286,  286,  314,  314,  314,  314,  279,  207,
      263,  258,  206,  256,  319,  255,  207,  110,   88,  110,
      254,  364,  253,  287,  252,   88,  319,  315,  251,  250,
      207,  110,  249,  110,  314,  314,  314,  314,  316,  316,
      316,  316,  364,  316,  316,  316,  316,  341,  341,  341,
      341,  117,  248,  117,  207,  247,  246,  315,  245,  324,
      321,  317,  321,  364,  244,  117,  317,  117,  324,  243,
      342,  242,  241,  240,  321,  207,  321,  341,  341,  341,
      341,  239,   88,  238,  364,  237,  341,  341,  341,  341,

       88,  341,  341,  341,  341,  234,  233,  232,  231,  321,
      342,  321,   88,   88,  230,  229,  226,   88,  225,  342,
       88,   88,  224,  321,  342,  321,   45,  223,  222,   45,
       45,   45,   45,   45,   45,   47,  221,   44,   47,   47,
       47,   48,  114,  181,   48,  174,   48,   48,   48,   48,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  115,
      173,  115,  115,  115,  115,  115,  115,  115,  128,  128,
      133,  133,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  205,  205,  205,  205,  215,  215,  215,  215,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  262,  262,

      262,  262,  262,  262,  262,  262,  262,  272,  172,  272,
      274,  274,  274,  274,  282,  169,  282,  284,  284,  284,
      284,  318,  168,  318,  323,  167,  323,  164,  163,   88,
      162,  161,  158,  157,   88,  156,  155,  154,  153,  152,
      151,  150,  149,  148,  147,  146,  143,  142,  141,  140,
      139,   44,  132,  127,  114,   66,   59,  108,   59,  107,
      106,   98,   91,   87,   44,   44,   66,   44,   44,   46,
       44,  364,    3,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,

      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364
    } ;

static const flex_int16_t yy_chk[1047] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   11,   15,   30,   17,   16,   17,   17,
       17,   17,   22,   22,   18,   30,   15,   16,   16,   18,
       11,   24,   24,   27,   31,   40,   31,   18,   19,   34,

       19,   19,   19,   19,   40,   31,   34,   34,  106,   27,
       43,  106,   19,   19,   19,   19,  100,   19,  375,   19,
       56,   56,   28,   19,   28,   19,   29,   19,   19,   19,
       32,   28,  100,   29,  373,   19,   96,   29,   32,   36,
       29,   32,   96,   36,   32,   39,   19,   20,  204,   20,
       20,   20,   20,   43,   37,  114,   39,   39,   36,   39,
      114,   39,   20,   20,   20,  363,   20,   62,   62,  204,
       37,  362,   20,   37,   68,   68,   20,   20,   20,   74,
       74,   90,   90,  361,   20,   50,   50,   50,   50,   53,
       53,   53,   53,  104,  125,  125,  125,  125,   50,   50,

       50,  104,   53,   53,   53,  148,  148,  360,   50,   55,
       55,   55,   50,   50,   50,  359,   53,   53,   53,   54,
       54,   54,   54,   58,  158,   58,   55,  158,   58,   58,
       58,   58,   55,  358,  105,  357,   54,   61,   61,   61,
       61,  356,   54,  355,   55,   64,   64,   64,   64,   65,
       65,   65,   65,  105,   54,  199,  199,  105,  212,  212,
       61,  108,  108,  108,  108,  108,  184,  354,   64,  214,
      353,  184,   65,  109,  109,  109,  109,  111,  199,  111,
      352,  212,  111,  111,  111,  111,  112,  112,  112,  112,
      214,  351,  118,  350,  118,  349,  109,  118,  118,  118,

      118,  203,  263,  119,  119,  119,  203,  263,  348,  112,
      116,  116,  116,  116,  347,  346,  345,  122,  122,  122,
      122,  344,  203,  116,  116,  116,  119,  123,  123,  123,
      123,  124,  124,  116,  343,  340,  339,  116,  116,  116,
      122,  338,  126,  126,  126,  126,  337,  336,  124,  335,
      123,  131,  131,  128,  124,  126,  334,  126,  129,  129,
      129,  130,  130,  130,  130,  126,  124,  333,  131,  126,
      213,  126,  128,  128,  131,  213,  133,  332,  128,  331,
      330,  129,  329,  328,  130,  327,  131,  209,  209,  209,
      128,  213,  269,  269,  128,  133,  133,  134,  134,  134,

      134,  133,  135,  135,  135,  135,  136,  136,  136,  136,
      209,  326,  325,  133,  313,  269,  312,  133,  311,  310,
      134,  137,  137,  137,  137,  135,  309,  308,  307,  136,
      182,  182,  182,  182,  182,  186,  186,  186,  186,  187,
      187,  187,  187,  306,  137,  272,  188,  188,  188,  188,
      272,  191,  191,  191,  191,  305,  304,  303,  186,  188,
      302,  188,  192,  192,  192,  192,  272,  301,  300,  188,
      299,  281,  281,  188,  191,  188,  193,  193,  193,  193,
      194,  194,  194,  194,  298,  192,  297,  196,  196,  196,
      196,  197,  197,  194,  281,  194,  296,  295,  200,  200,

      200,  200,  294,  194,  205,  293,  292,  194,  197,  194,
      196,  200,  208,  200,  197,  202,  202,  202,  202,  291,
      290,  200,  289,  205,  205,  200,  197,  200,  207,  205,
      207,  208,  208,  207,  207,  207,  207,  208,  202,  215,
      288,  205,  216,  211,  211,  205,  262,  259,  258,  208,
      257,  256,  255,  208,  210,  210,  210,  210,  215,  215,
      211,  216,  216,  253,  215,  252,  211,  216,  218,  218,
      218,  218,  219,  219,  219,  219,  215,  210,  211,  216,
      215,  251,  250,  216,  220,  220,  220,  220,  249,  273,
      248,  218,  247,  246,  273,  219,  260,  260,  260,  260,

      245,  261,  261,  261,  261,  244,  243,  220,  242,  260,
      273,  260,  265,  265,  265,  265,  241,  239,  238,  260,
      237,  268,  268,  260,  261,  260,  266,  266,  266,  266,
      236,  267,  267,  267,  267,  265,  235,  234,  268,  266,
      233,  266,  232,  231,  268,  270,  270,  270,  270,  266,
      274,  230,  282,  266,  267,  266,  268,  282,  270,  229,
      270,  271,  271,  271,  271,  228,  280,  280,  270,  274,
      274,  227,  270,  282,  270,  276,  276,  276,  276,  277,
      277,  277,  277,  280,  271,  284,  226,  274,  283,  280,
      225,  274,  277,  283,  277,  279,  279,  279,  279,  224,

      223,  280,  277,  222,  284,  284,  277,  221,  277,  283,
      287,  287,  287,  287,  314,  314,  314,  314,  279,  318,
      189,  183,  284,  181,  318,  180,  284,  314,  179,  314,
      178,  319,  177,  287,  176,  175,  319,  314,  174,  173,
      318,  314,  172,  314,  315,  315,  315,  315,  316,  316,
      316,  316,  319,  317,  317,  317,  317,  320,  320,  320,
      320,  316,  171,  316,  323,  170,  169,  315,  168,  323,
      320,  316,  320,  324,  167,  316,  317,  316,  324,  166,
      320,  165,  164,  163,  320,  323,  320,  322,  322,  322,
      322,  162,  161,  160,  324,  159,  341,  341,  341,  341,

      157,  342,  342,  342,  342,  156,  155,  154,  153,  341,
      322,  341,  152,  151,  150,  149,  147,  146,  145,  341,
      144,  143,  142,  341,  342,  341,  365,  141,  140,  365,
      365,  365,  365,  365,  365,  366,  139,  138,  366,  366,
      366,  367,  113,  107,  367,  103,  367,  367,  367,  367,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  369,
      102,  369,  369,  369,  369,  369,  369,  369,  370,  370,
      371,  371,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  374,  374,  374,  374,  376,  376,  376,  376,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  378,  378,

      378,  378,  378,  378,  378,  378,  378,  379,  101,  379,
      380,  380,  380,  380,  381,   99,  381,  382,  382,  382,
      382,  383,   98,  383,  384,   97,  384,   95,   94,   93,
       92,   91,   89,   87,   86,   85,   84,   83,   82,   81,
       80,   79,   78,   77,   76,   75,   73,   72,   71,   70,
       69,   67,   63,   60,   51,   49,   48,   46,   45,   42,
       41,   38,   35,   33,   26,   23,   21,   14,   10,    8,
        7,    3,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,

      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[10] =
    {   0,
0, 0, 0, 0, 1, 1, 1, 0, 0,     };

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "java_scanner.l"
#line 2 "java_scanner.l"
   #include <bits/stdc++.h>
   using namespace std;
 
   map<string,vector<string> > mp;
   vector<vector<string> > vec;
  
#line 782 "lex.yy.cc"
#line 783 "lex.yy.cc"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
#define ECHO LexerOutput( yytext, yyleng )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
\
	if ( (int)(result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) LexerError( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
#define YY_DECL int yyFlexLexer::yylex()
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin.rdbuf(std::cin.rdbuf());

		if ( ! yyout )
			yyout.rdbuf(std::cout.rdbuf());

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 121 "java_scanner.l"

#line 917 "lex.yy.cc"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 365 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 973 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 122 "java_scanner.l"
{if(mp.find(YYText())==mp.end()){
                                                        mp[YYText()] = {YYText(),"Keyword","1"};
                                                        vec.push_back({YYText(),"Keyword","1"});
                                                 }
                                                  else{
                                                     auto it = find(vec.begin(),vec.end(),mp[YYText()]);
                                                     vec[it-vec.begin()] = {YYText(),"Keyword",to_string(stoi(mp[YYText()][2])+1)};
                                                     mp[YYText()] = {YYText(),"Keyword",to_string(stoi(mp[YYText()][2])+1)};                    
                                                  }
                                                }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 134 "java_scanner.l"
{if(mp.find(YYText())==mp.end()){
                                                       mp[YYText()] = {YYText(),"Operator","1"};
                                                       vec.push_back({YYText(),"Operator","1"});
                                                  }
                                                   else{
                                                      auto it = find(vec.begin(),vec.end(),mp[YYText()]);
                                                      vec[it-vec.begin()] = {YYText(),"Operator",to_string(stoi(mp[YYText()][2])+1)};
                                                      mp[YYText()] = {YYText(),"Operator",to_string(stoi(mp[YYText()][2])+1)};                    
                                                  }
                                               }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 146 "java_scanner.l"
{if(mp.find(YYText())==mp.end()){
                                                        mp[YYText()] = {YYText(),"Separator","1"};
                                                        vec.push_back({YYText(),"Separator","1"});
                                                 }
                                                  else{
                                                     auto it = find(vec.begin(),vec.end(),mp[YYText()]);
                                                     vec[it-vec.begin()] = {YYText(),"Separator",to_string(stoi(mp[YYText()][2])+1)};
                                                     mp[YYText()] = {YYText(),"Separator",to_string(stoi(mp[YYText()][2])+1)};                    
                                                  }
                                                }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 158 "java_scanner.l"
{if(mp.find(YYText())==mp.end()){
                                                        mp[YYText()] = {YYText(),"Identifier","1"};
                                                        vec.push_back({YYText(),"Identifier","1"});
                                                 }
                                                  else{
                                                     auto it = find(vec.begin(),vec.end(),mp[YYText()]);
                                                     vec[it-vec.begin()] = {YYText(),"Identifier",to_string(stoi(mp[YYText()][2])+1)};
                                                     mp[YYText()] = {YYText(),"Identifier",to_string(stoi(mp[YYText()][2])+1)};                    
                                                  }
                                                }
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 170 "java_scanner.l"
{if(mp.find(YYText())==mp.end())
                                                   {
                                                        mp[YYText()] = {YYText(),"Literal","1"};
                                                        vec.push_back({YYText(),"Literal","1"});
                                                 }
                                                  else{
                                                     auto it = find(vec.begin(),vec.end(),mp[YYText()]);
                                                     vec[it-vec.begin()] = {YYText(),"Literal",to_string(stoi(mp[YYText()][2])+1)};
                                                     mp[YYText()] = {YYText(),"Literal",to_string(stoi(mp[YYText()][2])+1)};                    
                                                  }
                                                }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 185 "java_scanner.l"
/* This is to eat up comments and return nothing */
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 188 "java_scanner.l"
/* This is to eat up blanks,whitespace and line terminators */
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 191 "java_scanner.l"
{printf("Error: Illegal character %s, in line number %d\n",YYText(),yylineno);
                                                 return 0;
                                                 }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 194 "java_scanner.l"
ECHO;
	YY_BREAK
#line 1080 "lex.yy.cc"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin.rdbuf();
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* The contents of this function are C++ specific, so the () macro is not used.
 * This constructor simply maintains backward compatibility.
 * DEPRECATED
 */
yyFlexLexer::yyFlexLexer( std::istream* arg_yyin, std::ostream* arg_yyout ):
	yyin(arg_yyin ? arg_yyin->rdbuf() : std::cin.rdbuf()),
	yyout(arg_yyout ? arg_yyout->rdbuf() : std::cout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::yyFlexLexer( std::istream& arg_yyin, std::ostream& arg_yyout ):
	yyin(arg_yyin.rdbuf()),
	yyout(arg_yyout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::ctor_common()
{
	yy_c_buf_p = 0;
	yy_init = 0;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = NULL;

	yy_buffer_stack = NULL;
	yy_buffer_stack_top = 0;
	yy_buffer_stack_max = 0;

	yy_state_buf = 0;

}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::~yyFlexLexer()
{
	delete [] yy_state_buf;
	yyfree( yy_start_stack  );
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yyfree( yy_buffer_stack  );
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream& new_in, std::ostream& new_out )
{
	// was if( new_in )
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE  ) );

	// was if( new_out )
	yyout.rdbuf(new_out.rdbuf());
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream* new_in, std::ostream* new_out )
{
	if( ! new_in ) {
		new_in = &yyin;
	}

	if ( ! new_out ) {
		new_out = &yyout;
	}

	switch_streams(*new_in, *new_out);
}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
{
	if ( yyin.eof() || yyin.fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin.get( buf[0] );

	if ( yyin.eof() )
		return 0;

	if ( yyin.bad() )
		return -1;

	return 1;

#else
	(void) yyin.read( buf, max_size );

	if ( yyin.bad() )
		return -1;
	else
		return yyin.gcount();
#endif
}

void yyFlexLexer::LexerOutput( const char* buf, int size )
{
	(void) yyout.write( buf, size );
}

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
int yyFlexLexer::yy_get_next_buffer()
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    yy_state_type yyFlexLexer::yy_get_previous_state()
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 365 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 365 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 364);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT
    void yyFlexLexer::yyunput( int c, char* yy_bp)
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}
#endif

    int yyFlexLexer::yyinput()
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyFlexLexer::yyrestart( std::istream& input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Delegate to the new version that takes an istream reference.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
void yyFlexLexer::yyrestart( std::istream* input_file )
{
	if( ! input_file ) {
		input_file = &yyin;
	}
	yyrestart( *input_file );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

    void yyFlexLexer::yy_load_buffer_state()
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin.rdbuf(YY_CURRENT_BUFFER_LVALUE->yy_input_file);
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream& file, int size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Delegate creation of buffers to the new version that takes an istream reference.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
	YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream* file, int size )
{
	return yy_create_buffer( *file, size );
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, std::istream& file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file.rdbuf();
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

	b->yy_is_interactive = 0;
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yyFlexLexer::yypush_buffer_state (YY_BUFFER_STATE new_buffer)
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yyFlexLexer::yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
void yyFlexLexer::yyensure_buffer_stack(void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

    void yyFlexLexer::yy_push_state( int _new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_size_t) (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc( new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc(
					(void *) (yy_start_stack), new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(_new_state);
}

    void yyFlexLexer::yy_pop_state()
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    int yyFlexLexer::yy_top_state()
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

void yyFlexLexer::LexerError( const char* msg )
{
    	std::cerr << msg << std::endl;
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 194 "java_scanner.l"



int main(int argc, char **argv)
{
++argv, --argc;      /* Skip over the program name */
FlexLexer* scanner = new yyFlexLexer;
ifstream input;
if (argc > 0){
  input.open(argv[0]);
  scanner->switch_streams(input,cout);
}
scanner->yylex();
ofstream outputFile("output.csv");
outputFile << "Lexeme"<<","<<"Token"<<","<<"Count"<<"\n";
for(auto i=vec.begin();i!=vec.end();i++){
  outputFile<< (*i)[0]<<","<<(*i)[1]<<","<<(*i)[2]<<"\n";
}
outputFile.close();
return 0;
}




